### ISSUE TITLE
Cannot find typescript, server failed to start

### ISSUE THREAD

**Issue by CGQAQ** [denoland/vscode_deno#179]
**To Reproduce**

1. install vscode-deno
2. reload

**Screenshots**

![image](https://user-images.githubusercontent.com/15936231/92257604-176cbb00-ef08-11ea-8820-558ee1fb88e7.png)

**Versions**

vscode: 1.48.2
deno: 1.3.1
extension: 2.1.1

**Comment by CGQAQ** [comment]
works on 2.1.2
